version: '2'

services:
  app:
    image: node:14
    working_dir: /home/node/app
    command: "npm start"
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
    volumes:
      - .:/home/node/app
  mysql:
    image: mysql:5.7
    restart: always
    container_name: projetocat
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=cache
    ports:
      - "3306:3306"
    volumes:
      - ./cache:/var/lib/cache
      